version: '3.7'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        ports: 
            - 5432:5432
        logging:
            options:
                max-size: 10m
                max-file: "3"
    pgadmin:
        image: dpage/pgadmin4
        environment: 
            - PGADMIN_DEFAULT_EMAIL=postgres@postgres.com
            - PGADMIN_DEFAULT_PASSWORD=test
        ports: 
            - "80:80"